In [1]:
import pandas as pd
df1=pd.read_excel("HR_1 (1).xlsx")
print(df1.head(10))

   Age Attrition     BusinessTravel  DailyRate       Department  \
0   31        No         Non-Travel        158         Software
1   38        No      Travel_Rarely        985  Human Resources
2   59       Yes         Non-Travel       1273            Sales
3   52       Yes      Travel_Rarely        480          Support
4   32        No         Non-Travel        543  Human Resources
5   19       Yes         Non-Travel        779         Hardware
6   42       Yes         Non-Travel        934          Support
7   30        No      Travel_Rarely        380          Support
8   41        No  Travel_Frequently       1464         Software
9   45        No  Travel_Frequently       1020  Human Resources

   DistanceFromHome  Education    EducationField  EmployeeCount  \
0                 7          3           Medical              1
1                33          5     Life Sciences              1
2                 5          2  Technical Degree              1
3                 2          5         Marketing              1
4                 7          5   Human Resources              1
5                43          1           Medical              1
6                26          4   Human Resources              1
7                19          3         Marketing              1
8                16          1     Life Sciences              1
9                17          5     Life Sciences              1

   EmployeeNumber  EnvironmentSatisfaction  Gender  HourlyRate  \
0               1                        3    Male          42
1               2                        1  Female          66
2               3                        4  Female          96
3               4                        4  Female          71
4               5                        2    Male         122
5               6                        2  Female         195
6               7                        2  Female          80
7               8                        4    Male         165
8               9                        3    Male         134
9              10                        4  Female         137

   JobInvolvement  JobLevel                    JobRole  JobSatisfaction  \
0               2         3                  Developer                1
1               2         4  Healthcare Representative                3
2               1         3     Manufacturing Director                2
3               2         4            Human Resources                1
4               3         3                    Manager                2
5               4         3          Research Director                3
6               3         5            Sales Executive                4
7               1         4            Human Resources                4
8               1         2                    Manager                4
9               2         4                    Manager                2

  MaritalStatus
0       Married
1        Single
2       Married
3       Married
4      Divorced
5       Married
6      Divorced
7        Single
8      Divorced
9       Married

In [3]:
print(df1.info())

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      50000 non-null  int64
 1   Attrition                50000 non-null  str
 2   BusinessTravel           50000 non-null  str
 3   DailyRate                50000 non-null  int64
 4   Department               50000 non-null  str
 5   DistanceFromHome         50000 non-null  int64
 6   Education                50000 non-null  int64
 7   EducationField           50000 non-null  str
 8   EmployeeCount            50000 non-null  int64
 9   EmployeeNumber           50000 non-null  int64
 10  EnvironmentSatisfaction  50000 non-null  int64
 11  Gender                   50000 non-null  str
 12  HourlyRate               50000 non-null  int64
 13  JobInvolvement           50000 non-null  int64
 14  JobLevel                 50000 non-null  int64
 15  JobRole                  50000 non-null  str
 16  JobSatisfaction          50000 non-null  int64
 17  MaritalStatus            50000 non-null  str
dtypes: int64(11), str(7)
memory usage: 6.9 MB
None

In [4]:
df1.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.0,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,38.971480,798.677560,25.539780,3.004600,1.0,25000.500000,2.498360,115.432940,2.502620,2.994640,2.487380
std,12.420834,405.080217,14.339956,1.414249,0.0,14433.901067,1.119671,49.424867,1.120544,1.415998,1.116309
min,18.000000,100.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000
25%,28.000000,445.000000,13.000000,2.000000,1.0,12500.750000,1.000000,73.000000,1.000000,2.000000,1.000000
50%,39.000000,798.000000,25.000000,3.000000,1.0,25000.500000,2.000000,116.000000,3.000000,3.000000,2.000000
75%,50.000000,1151.000000,38.000000,4.000000,1.0,37500.250000,4.000000,158.000000,4.000000,4.000000,3.000000
max,60.000000,1500.000000,50.000000,5.000000,1.0,50000.000000,4.000000,200.000000,4.000000,5.000000,4.000000

In [5]:
import pandas as pd
df2=pd.read_excel("HR_2 (1).xlsx")
print(df2.head())

   Employee ID  MonthlyIncome  MonthlyRate  NumCompaniesWorked Over18  \
0            6          41552      1246560                   3      Y
1            7           5303       148484                   3      Y
2            8          28555       571100                   2      Y
3           11          10587        95283                   0      Y
4           13          34153       648907                   7      Y

  OverTime  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  \
0      Yes                 15                  4                         3
1       No                 45                  4                         1
2      Yes                 35                  3                         2
3      Yes                 47                  4                         2
4       No                 17                  1                         3

   StandardHours  StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0             80                 1                 33                      4
1             80                 1                  4                      3
2             80                 1                  2                      2
3             80                 1                 38                      3
4             80                 1                 30                      2

   WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                2              16                   4
1                4               2                   1
2                2               2                   2
3                4              24                  19
4                2              15                   3

   YearsSinceLastPromotion  YearsWithCurrManager
0                       14                     3
1                        1                     2
2                        2                     2
3                        8                     6
4                        8                     4

In [6]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Employee ID               50000 non-null  int64
 1   MonthlyIncome             50000 non-null  int64
 2   MonthlyRate               50000 non-null  int64
 3   NumCompaniesWorked        50000 non-null  int64
 4   Over18                    50000 non-null  str
 5   OverTime                  50000 non-null  str
 6   PercentSalaryHike         50000 non-null  int64
 7   PerformanceRating         50000 non-null  int64
 8   RelationshipSatisfaction  50000 non-null  int64
 9   StandardHours             50000 non-null  int64
 10  StockOptionLevel          50000 non-null  int64
 11  TotalWorkingYears         50000 non-null  int64
 12  TrainingTimesLastYear     50000 non-null  int64
 13  WorkLifeBalance           50000 non-null  int64
 14  YearsAtCompany            50000 non-null  int64
 15  YearsInCurrentRole        50000 non-null  int64
 16  YearsSinceLastPromotion   50000 non-null  int64
 17  YearsWithCurrManager      50000 non-null  int64
dtypes: int64(16), str(2)
memory usage: 6.9 MB

In [7]:
df2.describe()

,Employee ID,MonthlyIncome,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,50000.000000,50000.00000,5.000000e+04,50000.000000,50000.00000,50000.000000,50000.000000,50000.0,50000.000000,50000.000000,50000.000000,50000.00000,50000.00000,50000.000000,50000.000000,50000.000000
mean,25000.500000,26015.78126,4.040436e+05,3.999000,24.61832,2.495960,2.502220,80.0,2.503780,20.496860,3.493980,2.49872,10.77110,5.907300,5.871820,5.889040
std,14433.901067,14410.97750,3.401908e+05,2.582373,14.40500,1.118092,1.117918,0.0,1.118933,11.575819,1.708152,1.11412,8.93423,6.034378,5.999056,6.009613
min,1.000000,1001.00000,1.007000e+03,0.000000,0.00000,1.000000,1.000000,80.0,1.000000,1.000000,1.000000,1.00000,1.00000,1.000000,1.000000,1.000000
25%,12500.750000,13519.75000,1.228410e+05,2.000000,12.00000,1.000000,2.000000,80.0,2.000000,11.000000,2.000000,2.00000,3.00000,1.000000,2.000000,1.000000
50%,25000.500000,25988.50000,3.106300e+05,4.000000,25.00000,2.000000,2.000000,80.0,3.000000,20.000000,3.000000,2.00000,8.00000,4.000000,4.000000,4.000000
75%,37500.250000,38460.25000,6.105750e+05,6.000000,37.00000,3.000000,4.000000,80.0,4.000000,31.000000,5.000000,3.00000,16.00000,8.000000,8.000000,8.000000
max,50000.000000,50999.00000,1.528290e+06,8.000000,49.00000,4.000000,4.000000,80.0,4.000000,40.000000,6.000000,4.00000,40.00000,40.000000,40.000000,40.000000

In [16]:
import pandas as pd
df1=pd.read_excel("HR_1 (1).xlsx")
df2=pd.read_excel("HR_2 (1).xlsx")
merged_file = pd.merge(df1, df2,
                     left_on='EmployeeNumber',  
                     right_on='Employee ID',how='inner')      
merged_file.to_excel('HR_merged_file.xlsx', index=False)
print("Merge completed successfully!")

Merge completed successfully!

In [17]:
import pandas as pd
df1=pd.read_excel("HR_merged_file.xlsx")
print(df1.info())

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 36 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       50000 non-null  int64
 1   Attrition                 50000 non-null  str
 2   BusinessTravel            50000 non-null  str
 3   DailyRate                 50000 non-null  int64
 4   Department                50000 non-null  str
 5   DistanceFromHome          50000 non-null  int64
 6   Education                 50000 non-null  int64
 7   EducationField            50000 non-null  str
 8   EmployeeCount             50000 non-null  int64
 9   EmployeeNumber            50000 non-null  int64
 10  EnvironmentSatisfaction   50000 non-null  int64
 11  Gender                    50000 non-null  str
 12  HourlyRate                50000 non-null  int64
 13  JobInvolvement            50000 non-null  int64
 14  JobLevel                  50000 non-null  int64
 15  JobRole                   50000 non-null  str
 16  JobSatisfaction           50000 non-null  int64
 17  MaritalStatus             50000 non-null  str
 18  Employee ID               50000 non-null  int64
 19  MonthlyIncome             50000 non-null  int64
 20  MonthlyRate               50000 non-null  int64
 21  NumCompaniesWorked        50000 non-null  int64
 22  Over18                    50000 non-null  str
 23  OverTime                  50000 non-null  str
 24  PercentSalaryHike         50000 non-null  int64
 25  PerformanceRating         50000 non-null  int64
 26  RelationshipSatisfaction  50000 non-null  int64
 27  StandardHours             50000 non-null  int64
 28  StockOptionLevel          50000 non-null  int64
 29  TotalWorkingYears         50000 non-null  int64
 30  TrainingTimesLastYear     50000 non-null  int64
 31  WorkLifeBalance           50000 non-null  int64
 32  YearsAtCompany            50000 non-null  int64
 33  YearsInCurrentRole        50000 non-null  int64
 34  YearsSinceLastPromotion   50000 non-null  int64
 35  YearsWithCurrManager      50000 non-null  int64
dtypes: int64(27), str(9)
memory usage: 13.7 MB
None